package com.androidandrew.fleetio_assessment.fake

object FakeVehicleSource {
    const val numVehicles = 10

    val detailResponseEmptyDriver = """
    {
  "id": 1851804,
  "meter_unit": "km",
  "name": "258218",
  "secondary_meter": false,
  "secondary_meter_unit": null,
  "vehicle_status_name": "Active",
  "current_location_entry_id": 416049688,
  "meter_name": "Odometer",
  "secondary_meter_name": "Secondary Meter",
  "primary_meter_usage_per_day": "52.4",
  "secondary_meter_usage_per_day": "0.0",
  "created_at": "2022-04-25T09:34:40.055-07:00",
  "updated_at": "2022-11-10T23:48:34.128-08:00",
  "current_meter_value": 170150,
  "current_meter_date": "2022-11-10",
  "secondary_meter_value": 0,
  "secondary_meter_date": null,
  "color": null,
  "license_plate": null,
  "make": "Peterbilt",
  "model": "389",
  "vin": "1XPXD49X7JD468892",
  "year": 2018,
  "type_name": "Semi-Trailer Truck",
  "default_image_url": null,
  "default_image_url_medium": null,
  "default_image_url_small": null,
  "default_image_url_large": null,
  "driver": {},
  "current_location_entry": {
    "id": 416049688,
    "locatable_type": "FuelEntry",
    "locatable_id": 42775473,
    "date": "2022-11-09T22:14:00.000-08:00",
    "created_at": "2022-11-10T23:47:23.035-08:00",
    "updated_at": "2022-11-10T23:48:12.296-08:00",
    "contact_id": null,
    "address": "433 NE County Rd, Crane, TX 79731, USA",
    "is_current": true,
    "item_type": "Vehicle",
    "item_id": 1851804,
    "vehicle_id": 1851804,
    "location": "POINT (-102.348618 31.406998)",
    "address_components": {
      "street_number": "433",
      "street": "Northeast County Road",
      "city": "Crane",
      "region": "Texas",
      "region_short": "TX",
      "country": "United States",
      "country_short": "US",
      "postal_code": "79731"
    },
    "geolocation": {
      "latitude": 31.406998,
      "longitude": -102.348618
    }
  },
  "documents_including_nested_resources_count": 0
}
""".trimIndent()

    const val fakeResponse = """
    [
      {
        "id": 2128326,
        "account_id": 18,
        "archived_at": null,
        "fuel_type_id": null,
        "fuel_type_name": null,
        "fuel_volume_units": "us_gallons",
        "group_id": 184261,
        "group_name": "001 TEST Default",
        "meter_unit": "mi",
        "name": "001",
        "ownership": "Owned",
        "secondary_meter": false,
        "secondary_meter_unit": null,
        "system_of_measurement": "imperial",
        "vehicle_status_id": 3261,
        "vehicle_status_name": "Active",
        "vehicle_status_color": "blue",
        "vehicle_type_id": 144,
        "vehicle_type_name": "Car",
        "fuel_entries_count": 1,
        "service_entries_count": 1,
        "service_reminders_count": 0,
        "vehicle_renewal_reminders_count": 0,
        "comments_count": 1,
        "documents_count": 4,
        "images_count": 3,
        "current_location_entry_id": 400194403,
        "is_sample": false,
        "in_service_date": null,
        "in_service_meter": null,
        "estimated_service_months": null,
        "estimated_replacement_mileage": null,
        "estimated_resale_price": null,
        "out_of_service_date": null,
        "out_of_service_meter": null,
        "meter_name": "Odometer",
        "secondary_meter_name": "Secondary Meter",
        "primary_meter_usage_per_day": "0.0",
        "secondary_meter_usage_per_day": "0.0",
        "created_at": "2022-10-07T13:34:45.551-07:00",
        "updated_at": "2022-11-01T21:05:33.010-07:00",
        "current_meter_value": 1,
        "current_meter_date": "2022-10-17",
        "secondary_meter_value": 0,
        "secondary_meter_date": null,
        "group_ancestry": "001 TEST Default",
        "color": null,
        "license_plate": null,
        "make": null,
        "model": null,
        "registration_expiration_month": 0,
        "registration_state": null,
        "trim": null,
        "vin": null,
        "year": null,
        "loan_account_number": null,
        "loan_ended_at": null,
        "loan_interest_rate": null,
        "loan_notes": null,
        "loan_started_at": null,
        "loan_vendor_id": null,
        "loan_vendor_name": null,
        "custom_fields": {
          "telematics_subscription": "",
          "restrict": "",
          "warranty_expiration": "",
          "warranty_type": "",
          "toll_pass_number": "",
          "rear_camera_enabled": "false",
          "vehicle_cleanliness": "false",
          "test": "false",
          "checkbox_filter_test": "false",
          "manufacturer_model": "",
          "extra_rextra_read_all_about_it_this_is_a_super_long_field_name_my_guyyy": ""
        },
        "inspection_schedules_count": 10,
        "issues_count": 0,
        "work_orders_count": 4,
        "type_name": "Car",
        "default_image_url": "https://d8g9nhlfs6lwh.cloudfront.net/ICM5IE9QT8WM1fWCGKhr?signature=e1bf387376847dc881ac46d80ac0ca089532483f5f55b64305fc232b5d0b5488&policy=eyJoYW5kbGUiOiJJQ001SUU5UVQ4V00xZldDR0tociIsImV4cGlyeSI6NDUzNDk0OTM0MywiY2FsbCI6WyJyZWFkIl19",
        "default_image_url_medium": "https://d8g9nhlfs6lwh.cloudfront.net/security=policy:eyJoYW5kbGUiOiJJQ001SUU5UVQ4V00xZldDR0tociIsImV4cGlyeSI6NDUzNDk0OTM0MywiY2FsbCI6WyJyZWFkIiwiY29udmVydCJdfQ==,signature:0b479c5ee7cf6c4e09f1942c423b8638e1ab219f73c4f1cce5962757da4423ed/resize=w:100,h:100,fit:crop/cache=expiry:max/rotate=exif:true/ICM5IE9QT8WM1fWCGKhr",
        "default_image_url_small": "https://d8g9nhlfs6lwh.cloudfront.net/security=policy:eyJoYW5kbGUiOiJJQ001SUU5UVQ4V00xZldDR0tociIsImV4cGlyeSI6NDUzNDk0OTM0MywiY2FsbCI6WyJyZWFkIiwiY29udmVydCJdfQ==,signature:0b479c5ee7cf6c4e09f1942c423b8638e1ab219f73c4f1cce5962757da4423ed/resize=w:45,h:45,fit:crop/cache=expiry:max/rotate=exif:true/ICM5IE9QT8WM1fWCGKhr",
        "default_image_url_large": "https://d8g9nhlfs6lwh.cloudfront.net/security=policy:eyJoYW5kbGUiOiJJQ001SUU5UVQ4V00xZldDR0tociIsImV4cGlyeSI6NDUzNDk0OTM0MywiY2FsbCI6WyJyZWFkIiwiY29udmVydCJdfQ==,signature:0b479c5ee7cf6c4e09f1942c423b8638e1ab219f73c4f1cce5962757da4423ed/resize=w:450,fit:scale/cache=expiry:max/rotate=exif:true/ICM5IE9QT8WM1fWCGKhr",
        "driver": {
          "id": 566231,
          "first_name": "00 test",
          "last_name": "(QA DO NOT TOUCH)",
          "full_name": "00 test (QA DO NOT TOUCH)",
          "default_image_url": null
        },
        "specs": {
          "engine_bore_with_units": null,
          "wheelbase_with_units": null
        },
        "external_ids": {
          "clearpathgps": null,
          "external_fuel_id": null,
          "fuel_id": null,
          "task_code": null,
          "traxxis_id": null
        },
        "ai_enabled": false,
        "assetable_type": "Vehicle",
        "current_location_entry": {
          "id": 400194403,
          "locatable_type": "SubmittedInspectionForm",
          "locatable_id": 26590292,
          "date": "2022-10-14T09:44:58.813-05:00",
          "created_at": "2022-10-14T09:45:01.345-05:00",
          "updated_at": "2022-10-14T09:45:01.842-05:00",
          "contact_id": null,
          "address": "1600 Amphitheatre Pkwy Building 43, Mountain View, CA 94043, USA",
          "is_current": true,
          "item_type": "Vehicle",
          "item_id": 2128326,
          "vehicle_id": 2128326,
          "location": "POINT (-122.08392 37.421494)",
          "address_components": {
            "street_number": "1600",
            "street": "Amphitheatre Parkway",
            "city": "Mountain View",
            "region": "California",
            "region_short": "CA",
            "country": "United States",
            "country_short": "US",
            "postal_code": "94043"
          },
          "geolocation": {
            "latitude": 37.421494,
            "longitude": -122.08392
          }
        }
      },
      {
        "id": 2128327,
        "account_id": 18,
        "archived_at": null,
        "fuel_type_id": null,
        "fuel_type_name": null,
        "fuel_volume_units": "us_gallons",
        "group_id": 184261,
        "group_name": "001 TEST Default",
        "meter_unit": "mi",
        "name": "002",
        "ownership": "Owned",
        "secondary_meter": false,
        "secondary_meter_unit": null,
        "system_of_measurement": "imperial",
        "vehicle_status_id": 3261,
        "vehicle_status_name": "Active",
        "vehicle_status_color": "blue",
        "vehicle_type_id": 774956,
        "vehicle_type_name": "Penguin",
        "fuel_entries_count": 0,
        "service_entries_count": 0,
        "service_reminders_count": 0,
        "vehicle_renewal_reminders_count": 0,
        "comments_count": 0,
        "documents_count": 0,
        "images_count": 0,
        "current_location_entry_id": 397425427,
        "is_sample": false,
        "in_service_date": null,
        "in_service_meter": null,
        "estimated_service_months": null,
        "estimated_replacement_mileage": null,
        "estimated_resale_price": {
          "cents": 0,
          "currency_iso": "USD"
        },
        "out_of_service_date": null,
        "out_of_service_meter": null,
        "meter_name": "Odometer",
        "secondary_meter_name": "Secondary Meter",
        "primary_meter_usage_per_day": "0.0",
        "secondary_meter_usage_per_day": "0.0",
        "created_at": "2022-10-07T13:34:46.995-07:00",
        "updated_at": "2022-11-07T18:43:02.444-08:00",
        "current_meter_value": 2,
        "current_meter_date": "2022-10-09",
        "secondary_meter_value": 0,
        "secondary_meter_date": null,
        "group_ancestry": "001 TEST Default",
        "color": null,
        "license_plate": null,
        "make": null,
        "model": null,
        "registration_expiration_month": 0,
        "registration_state": null,
        "trim": null,
        "vin": null,
        "year": 2000,
        "loan_account_number": null,
        "loan_ended_at": null,
        "loan_interest_rate": null,
        "loan_notes": null,
        "loan_started_at": null,
        "loan_vendor_id": null,
        "loan_vendor_name": null,
        "custom_fields": {
          "telematics_subscription": "",
          "restrict": "",
          "warranty_expiration": "",
          "warranty_type": "",
          "toll_pass_number": "",
          "rear_camera_enabled": "false",
          "vehicle_cleanliness": "false",
          "test": "false",
          "checkbox_filter_test": "false",
          "manufacturer_model": "",
          "extra_rextra_read_all_about_it_this_is_a_super_long_field_name_my_guyyy": ""
        },
        "inspection_schedules_count": 11,
        "issues_count": 0,
        "work_orders_count": 0,
        "type_name": "Penguin",
        "default_image_url": null,
        "default_image_url_medium": null,
        "default_image_url_small": null,
        "default_image_url_large": null,
        "driver": {},
        "specs": {
          "id": 3121759,
          "vehicle_id": 2128327,
          "account_id": 18,
          "body_type": null,
          "body_subtype": null,
          "drive_type": null,
          "brake_system": null,
          "msrp_cents": null,
          "fuel_tank_capacity": null,
          "fuel_tank_2_capacity": null,
          "front_track_width": null,
          "ground_clearance": null,
          "height": null,
          "length": null,
          "rear_track_width": null,
          "width": null,
          "wheelbase": null,
          "front_tire_psi": null,
          "rear_tire_psi": null,
          "base_towing_capacity": null,
          "curb_weight": null,
          "gross_vehicle_weight_rating": null,
          "bed_length": null,
          "max_payload": null,
          "rear_axle_type": "",
          "front_tire_type": "",
          "front_wheel_diameter": "",
          "rear_tire_type": "",
          "rear_wheel_diameter": "",
          "epa_city": null,
          "epa_highway": null,
          "epa_combined": null,
          "engine_description": "",
          "engine_brand": "",
          "engine_aspiration": null,
          "engine_block_type": null,
          "engine_bore": null,
          "engine_cam_type": null,
          "engine_compression": null,
          "engine_cylinders": null,
          "engine_displacement": null,
          "fuel_induction": null,
          "fuel_quality": "",
          "max_hp": null,
          "max_torque": null,
          "oil_capacity": null,
          "redline_rpm": "",
          "engine_stroke": null,
          "engine_valves": null,
          "transmission_description": "",
          "transmission_brand": "",
          "transmission_type": null,
          "transmission_gears": null,
          "cargo_volume": null,
          "interior_volume": null,
          "passenger_volume": "",
          "created_at": "2022-10-29T05:08:21.448-07:00",
          "updated_at": "2022-10-29T05:08:21.448-07:00",
          "duty_type": null,
          "weight_class": null,
          "engine_bore_with_units": null,
          "wheelbase_with_units": null,
          "msrp": null
        },
        "external_ids": {
          "clearpathgps": null,
          "external_fuel_id": null,
          "fuel_id": null,
          "task_code": null,
          "traxxis_id": null
        },
        "ai_enabled": false,
        "assetable_type": "Vehicle",
        "current_location_entry": {
          "id": 397425427,
          "locatable_type": "SubmittedInspectionForm",
          "locatable_id": 26382433,
          "date": "2022-10-09T10:13:01.300-07:00",
          "created_at": "2022-10-09T10:13:01.549-07:00",
          "updated_at": "2022-10-09T10:13:01.827-07:00",
          "contact_id": null,
          "address": "8875 Alpen Way, Cottonwood Heights, UT 84121, USA",
          "is_current": true,
          "item_type": "Vehicle",
          "item_id": 2128327,
          "vehicle_id": 2128327,
          "location": "POINT (-111.79275 40.590027)",
          "address_components": {
            "street_number": "8875",
            "street": "Alpen Way",
            "city": "Cottonwood Heights",
            "region": "Utah",
            "region_short": "UT",
            "country": "United States",
            "country_short": "US",
            "postal_code": "84121"
          },
          "geolocation": {
            "latitude": 40.590027,
            "longitude": -111.79275
          }
        }
      },
      {
        "id": 2128328,
        "account_id": 18,
        "archived_at": null,
        "fuel_type_id": null,
        "fuel_type_name": null,
        "fuel_volume_units": "us_gallons",
        "group_id": 184261,
        "group_name": "001 TEST Default",
        "meter_unit": "mi",
        "name": "003",
        "ownership": "Owned",
        "secondary_meter": false,
        "secondary_meter_unit": null,
        "system_of_measurement": "imperial",
        "vehicle_status_id": 3261,
        "vehicle_status_name": "Active",
        "vehicle_status_color": "blue",
        "vehicle_type_id": 144,
        "vehicle_type_name": "Car",
        "fuel_entries_count": 0,
        "service_entries_count": 1,
        "service_reminders_count": 1,
        "vehicle_renewal_reminders_count": 0,
        "comments_count": 0,
        "documents_count": 0,
        "images_count": 0,
        "current_location_entry_id": null,
        "is_sample": false,
        "in_service_date": null,
        "in_service_meter": null,
        "estimated_service_months": null,
        "estimated_replacement_mileage": null,
        "estimated_resale_price": {
          "cents": 0,
          "currency_iso": "USD"
        },
        "out_of_service_date": null,
        "out_of_service_meter": null,
        "meter_name": "Odometer",
        "secondary_meter_name": "Secondary Meter",
        "primary_meter_usage_per_day": "0.0",
        "secondary_meter_usage_per_day": "0.0",
        "created_at": "2022-10-07T13:34:48.174-07:00",
        "updated_at": "2022-11-10T05:21:15.145-08:00",
        "current_meter_value": 0,
        "current_meter_date": null,
        "secondary_meter_value": 0,
        "secondary_meter_date": null,
        "group_ancestry": "001 TEST Default",
        "color": null,
        "license_plate": null,
        "make": null,
        "model": null,
        "registration_expiration_month": 0,
        "registration_state": null,
        "trim": null,
        "vin": null,
        "year": null,
        "loan_account_number": null,
        "loan_ended_at": null,
        "loan_interest_rate": null,
        "loan_notes": null,
        "loan_started_at": null,
        "loan_vendor_id": null,
        "loan_vendor_name": null,
        "custom_fields": {
          "telematics_subscription": "",
          "restrict": "",
          "warranty_expiration": "",
          "warranty_type": "1",
          "toll_pass_number": "",
          "rear_camera_enabled": "false",
          "vehicle_cleanliness": "false",
          "test": "false",
          "checkbox_filter_test": "false",
          "manufacturer_model": "",
          "extra_rextra_read_all_about_it_this_is_a_super_long_field_name_my_guyyy": ""
        },
        "inspection_schedules_count": 10,
        "issues_count": 0,
        "work_orders_count": 0,
        "type_name": "Car",
        "default_image_url": null,
        "default_image_url_medium": null,
        "default_image_url_small": null,
        "default_image_url_large": null,
        "driver": {},
        "specs": {
          "id": 3121799,
          "vehicle_id": 2128328,
          "account_id": 18,
          "body_type": null,
          "body_subtype": null,
          "drive_type": null,
          "brake_system": null,
          "msrp_cents": 0,
          "fuel_tank_capacity": null,
          "fuel_tank_2_capacity": null,
          "front_track_width": null,
          "ground_clearance": null,
          "height": null,
          "length": null,
          "rear_track_width": null,
          "width": null,
          "wheelbase": null,
          "front_tire_psi": null,
          "rear_tire_psi": null,
          "base_towing_capacity": null,
          "curb_weight": null,
          "gross_vehicle_weight_rating": null,
          "bed_length": null,
          "max_payload": null,
          "rear_axle_type": "",
          "front_tire_type": "",
          "front_wheel_diameter": "",
          "rear_tire_type": "",
          "rear_wheel_diameter": "",
          "epa_city": null,
          "epa_highway": null,
          "epa_combined": null,
          "engine_description": "",
          "engine_brand": "",
          "engine_aspiration": null,
          "engine_block_type": null,
          "engine_bore": null,
          "engine_cam_type": null,
          "engine_compression": null,
          "engine_cylinders": null,
          "engine_displacement": null,
          "fuel_induction": null,
          "fuel_quality": "",
          "max_hp": null,
          "max_torque": null,
          "oil_capacity": null,
          "redline_rpm": "",
          "engine_stroke": null,
          "engine_valves": null,
          "transmission_description": "",
          "transmission_brand": "",
          "transmission_type": null,
          "transmission_gears": null,
          "cargo_volume": null,
          "interior_volume": null,
          "passenger_volume": "",
          "created_at": "2022-10-29T06:54:50.670-07:00",
          "updated_at": "2022-10-29T06:54:50.670-07:00",
          "duty_type": null,
          "weight_class": null,
          "engine_bore_with_units": null,
          "wheelbase_with_units": null,
          "msrp": 0
        },
        "external_ids": {
          "clearpathgps": null,
          "external_fuel_id": null,
          "fuel_id": null,
          "task_code": null,
          "traxxis_id": null
        },
        "ai_enabled": false,
        "assetable_type": "Vehicle",
        "current_location_entry": {}
      },
      {
        "id": 2128329,
        "account_id": 18,
        "archived_at": null,
        "fuel_type_id": null,
        "fuel_type_name": null,
        "fuel_volume_units": "us_gallons",
        "group_id": 184261,
        "group_name": "001 TEST Default",
        "meter_unit": "mi",
        "name": "004",
        "ownership": "Owned",
        "secondary_meter": false,
        "secondary_meter_unit": null,
        "system_of_measurement": "imperial",
        "vehicle_status_id": 3261,
        "vehicle_status_name": "Active",
        "vehicle_status_color": "blue",
        "vehicle_type_id": 144,
        "vehicle_type_name": "Car",
        "fuel_entries_count": 0,
        "service_entries_count": 0,
        "service_reminders_count": 0,
        "vehicle_renewal_reminders_count": 0,
        "comments_count": 0,
        "documents_count": 0,
        "images_count": 0,
        "current_location_entry_id": null,
        "is_sample": false,
        "in_service_date": null,
        "in_service_meter": null,
        "estimated_service_months": null,
        "estimated_replacement_mileage": null,
        "estimated_resale_price": null,
        "out_of_service_date": null,
        "out_of_service_meter": null,
        "meter_name": "Odometer",
        "secondary_meter_name": "Secondary Meter",
        "primary_meter_usage_per_day": null,
        "secondary_meter_usage_per_day": null,
        "created_at": "2022-10-07T13:34:49.297-07:00",
        "updated_at": "2022-10-07T13:34:49.297-07:00",
        "current_meter_value": 0,
        "current_meter_date": null,
        "secondary_meter_value": 0,
        "secondary_meter_date": null,
        "group_ancestry": "001 TEST Default",
        "color": null,
        "license_plate": null,
        "make": null,
        "model": null,
        "registration_expiration_month": 0,
        "registration_state": null,
        "trim": null,
        "vin": null,
        "year": null,
        "loan_account_number": null,
        "loan_ended_at": null,
        "loan_interest_rate": null,
        "loan_notes": null,
        "loan_started_at": null,
        "loan_vendor_id": null,
        "loan_vendor_name": null,
        "custom_fields": {
          "telematics_subscription": "",
          "restrict": "",
          "warranty_expiration": "",
          "warranty_type": "",
          "toll_pass_number": "",
          "rear_camera_enabled": "false",
          "vehicle_cleanliness": "false",
          "test": "false",
          "checkbox_filter_test": "false",
          "manufacturer_model": "",
          "extra_rextra_read_all_about_it_this_is_a_super_long_field_name_my_guyyy": ""
        },
        "inspection_schedules_count": 10,
        "issues_count": 0,
        "work_orders_count": 0,
        "type_name": "Car",
        "default_image_url": null,
        "default_image_url_medium": null,
        "default_image_url_small": null,
        "default_image_url_large": null,
        "driver": {},
        "specs": {
          "engine_bore_with_units": null,
          "wheelbase_with_units": null
        },
        "external_ids": {
          "clearpathgps": null,
          "external_fuel_id": null,
          "fuel_id": null,
          "task_code": null,
          "traxxis_id": null
        },
        "ai_enabled": false,
        "assetable_type": "Vehicle",
        "current_location_entry": {}
      },
      {
        "id": 2128330,
        "account_id": 18,
        "archived_at": null,
        "fuel_type_id": null,
        "fuel_type_name": null,
        "fuel_volume_units": "us_gallons",
        "group_id": 184261,
        "group_name": "001 TEST Default",
        "meter_unit": "mi",
        "name": "005",
        "ownership": "Owned",
        "secondary_meter": false,
        "secondary_meter_unit": null,
        "system_of_measurement": "imperial",
        "vehicle_status_id": 3261,
        "vehicle_status_name": "Active",
        "vehicle_status_color": "blue",
        "vehicle_type_id": 144,
        "vehicle_type_name": "Car",
        "fuel_entries_count": 1,
        "service_entries_count": 2,
        "service_reminders_count": 0,
        "vehicle_renewal_reminders_count": 0,
        "comments_count": 0,
        "documents_count": 0,
        "images_count": 0,
        "current_location_entry_id": null,
        "is_sample": false,
        "in_service_date": null,
        "in_service_meter": null,
        "estimated_service_months": null,
        "estimated_replacement_mileage": null,
        "estimated_resale_price": {
          "cents": 0,
          "currency_iso": "USD"
        },
        "out_of_service_date": null,
        "out_of_service_meter": null,
        "meter_name": "Odometer",
        "secondary_meter_name": "Secondary Meter",
        "primary_meter_usage_per_day": "32.3",
        "secondary_meter_usage_per_day": "0.0",
        "created_at": "2022-10-07T13:34:50.276-07:00",
        "updated_at": "2022-11-09T11:33:08.879-08:00",
        "current_meter_value": 43000,
        "current_meter_date": "2022-11-04",
        "secondary_meter_value": 0,
        "secondary_meter_date": null,
        "group_ancestry": "001 TEST Default",
        "color": null,
        "license_plate": null,
        "make": null,
        "model": null,
        "registration_expiration_month": 0,
        "registration_state": null,
        "trim": null,
        "vin": "ABC-ABC-12345",
        "year": 1998,
        "loan_account_number": null,
        "loan_ended_at": null,
        "loan_interest_rate": null,
        "loan_notes": null,
        "loan_started_at": null,
        "loan_vendor_id": null,
        "loan_vendor_name": null,
        "custom_fields": {
          "telematics_subscription": "",
          "restrict": "",
          "warranty_expiration": "",
          "warranty_type": "1",
          "toll_pass_number": "",
          "rear_camera_enabled": "false",
          "vehicle_cleanliness": "false",
          "test": "false",
          "checkbox_filter_test": "false",
          "manufacturer_model": "",
          "extra_rextra_read_all_about_it_this_is_a_super_long_field_name_my_guyyy": ""
        },
        "inspection_schedules_count": 10,
        "issues_count": 1,
        "work_orders_count": 1,
        "type_name": "Car",
        "default_image_url": null,
        "default_image_url_medium": null,
        "default_image_url_small": null,
        "default_image_url_large": null,
        "driver": {},
        "specs": {
          "id": 3121740,
          "vehicle_id": 2128330,
          "account_id": 18,
          "body_type": null,
          "body_subtype": null,
          "drive_type": null,
          "brake_system": null,
          "msrp_cents": 0,
          "fuel_tank_capacity": null,
          "fuel_tank_2_capacity": null,
          "front_track_width": null,
          "ground_clearance": null,
          "height": null,
          "length": null,
          "rear_track_width": null,
          "width": null,
          "wheelbase": null,
          "front_tire_psi": null,
          "rear_tire_psi": null,
          "base_towing_capacity": null,
          "curb_weight": null,
          "gross_vehicle_weight_rating": null,
          "bed_length": null,
          "max_payload": null,
          "rear_axle_type": "",
          "front_tire_type": "",
          "front_wheel_diameter": "",
          "rear_tire_type": "",
          "rear_wheel_diameter": "",
          "epa_city": null,
          "epa_highway": null,
          "epa_combined": null,
          "engine_description": "",
          "engine_brand": "",
          "engine_aspiration": null,
          "engine_block_type": null,
          "engine_bore": null,
          "engine_cam_type": null,
          "engine_compression": null,
          "engine_cylinders": null,
          "engine_displacement": null,
          "fuel_induction": null,
          "fuel_quality": "",
          "max_hp": null,
          "max_torque": null,
          "oil_capacity": null,
          "redline_rpm": "",
          "engine_stroke": null,
          "engine_valves": null,
          "transmission_description": "",
          "transmission_brand": "",
          "transmission_type": null,
          "transmission_gears": null,
          "cargo_volume": null,
          "interior_volume": null,
          "passenger_volume": "",
          "created_at": "2022-10-29T03:58:59.424-07:00",
          "updated_at": "2022-10-29T03:58:59.424-07:00",
          "duty_type": null,
          "weight_class": null,
          "engine_bore_with_units": null,
          "wheelbase_with_units": null,
          "msrp": 0
        },
        "external_ids": {
          "clearpathgps": null,
          "external_fuel_id": null,
          "fuel_id": null,
          "task_code": null,
          "traxxis_id": null
        },
        "ai_enabled": false,
        "assetable_type": "Vehicle",
        "current_location_entry": {}
      },
      {
        "id": 1388383,
        "account_id": 18,
        "archived_at": null,
        "fuel_type_id": null,
        "fuel_type_name": null,
        "fuel_volume_units": "us_gallons",
        "group_id": 251829,
        "group_name": "001 TEST Parent",
        "meter_unit": "mi",
        "name": "00 Group Test Parent",
        "ownership": "Owned",
        "secondary_meter": true,
        "secondary_meter_unit": "hr",
        "system_of_measurement": "metric",
        "vehicle_status_id": 3263,
        "vehicle_status_name": "In Shop",
        "vehicle_status_color": "orange",
        "vehicle_type_id": 146,
        "vehicle_type_name": "Generator",
        "fuel_entries_count": 13,
        "service_entries_count": 16,
        "service_reminders_count": 4,
        "vehicle_renewal_reminders_count": 2,
        "comments_count": 3,
        "documents_count": 0,
        "images_count": 0,
        "current_location_entry_id": 357134349,
        "is_sample": false,
        "in_service_date": null,
        "in_service_meter": null,
        "estimated_service_months": null,
        "estimated_replacement_mileage": null,
        "estimated_resale_price": {
          "cents": 12300,
          "currency_iso": "USD"
        },
        "out_of_service_date": null,
        "out_of_service_meter": null,
        "meter_name": "Odometer",
        "secondary_meter_name": "Secondary Meter",
        "primary_meter_usage_per_day": "2298.8",
        "secondary_meter_usage_per_day": "9433.9",
        "created_at": "2021-02-28T16:43:28.158-08:00",
        "updated_at": "2022-11-09T05:26:11.664-08:00",
        "current_meter_value": 999999,
        "current_meter_date": "2022-10-01",
        "secondary_meter_value": 999999,
        "secondary_meter_date": "2022-10-01",
        "group_ancestry": "001 TEST Parent",
        "color": null,
        "license_plate": null,
        "make": "Subaru",
        "model": null,
        "registration_expiration_month": 0,
        "registration_state": "OK",
        "trim": null,
        "vin": "Q",
        "year": 1992,
        "loan_account_number": "",
        "loan_ended_at": "2023-03-01",
        "loan_interest_rate": null,
        "loan_notes": "",
        "loan_started_at": "2022-06-01",
        "loan_vendor_id": null,
        "loan_vendor_name": null,
        "loan_amount": 5000,
        "loan_payment": 100,
        "residual_value": null,
        "custom_fields": {
          "telematics_subscription": "Subscription C",
          "restrict": "2",
          "warranty_expiration": "2022-04-05",
          "warranty_type": "2",
          "toll_pass_number": "",
          "rear_camera_enabled": "false",
          "vehicle_cleanliness": "true",
          "test": "false",
          "checkbox_filter_test": "true",
          "manufacturer_model": "",
          "extra_rextra_read_all_about_it_this_is_a_super_long_field_name_my_guyyy": ""
        },
        "inspection_schedules_count": 13,
        "issues_count": 4,
        "work_orders_count": 68,
        "type_name": "Generator",
        "default_image_url": null,
        "default_image_url_medium": null,
        "default_image_url_small": null,
        "default_image_url_large": null,
        "driver": {
          "id": 566231,
          "first_name": "00 test",
          "last_name": "(QA DO NOT TOUCH)",
          "full_name": "00 test (QA DO NOT TOUCH)",
          "default_image_url": null
        },
        "specs": {
          "id": 2922271,
          "vehicle_id": 1388383,
          "account_id": 18,
          "body_type": null,
          "body_subtype": null,
          "drive_type": null,
          "brake_system": null,
          "msrp_cents": 22222,
          "fuel_tank_capacity": null,
          "fuel_tank_2_capacity": null,
          "front_track_width": null,
          "ground_clearance": null,
          "height": null,
          "length": null,
          "rear_track_width": null,
          "width": null,
          "wheelbase": null,
          "front_tire_psi": null,
          "rear_tire_psi": null,
          "base_towing_capacity": null,
          "curb_weight": null,
          "gross_vehicle_weight_rating": null,
          "bed_length": null,
          "max_payload": null,
          "rear_axle_type": "",
          "front_tire_type": "",
          "front_wheel_diameter": "",
          "rear_tire_type": "",
          "rear_wheel_diameter": "",
          "epa_city": null,
          "epa_highway": null,
          "epa_combined": null,
          "engine_description": "",
          "engine_brand": "",
          "engine_aspiration": null,
          "engine_block_type": null,
          "engine_bore": null,
          "engine_cam_type": null,
          "engine_compression": null,
          "engine_cylinders": null,
          "engine_displacement": null,
          "fuel_induction": null,
          "fuel_quality": "",
          "max_hp": null,
          "max_torque": null,
          "oil_capacity": null,
          "redline_rpm": "",
          "engine_stroke": null,
          "engine_valves": null,
          "transmission_description": "",
          "transmission_brand": "",
          "transmission_type": null,
          "transmission_gears": null,
          "cargo_volume": null,
          "interior_volume": null,
          "passenger_volume": "",
          "created_at": "2022-08-11T11:06:48.852-07:00",
          "updated_at": "2022-08-11T11:06:48.852-07:00",
          "duty_type": null,
          "weight_class": null,
          "engine_bore_with_units": null,
          "wheelbase_with_units": null,
          "msrp": 222.22
        },
        "external_ids": {
          "clearpathgps": "",
          "external_fuel_id": "",
          "fuel_id": "",
          "task_code": "",
          "traxxis_id": "1"
        },
        "ai_enabled": false,
        "assetable_type": "Vehicle",
        "current_location_entry": {
          "id": 357134349,
          "locatable_type": "SubmittedInspectionForm",
          "locatable_id": 23969389,
          "date": "2022-07-28T12:08:57.385-05:00",
          "created_at": "2022-07-28T12:08:57.571-05:00",
          "updated_at": "2022-07-28T12:10:27.928-05:00",
          "contact_id": null,
          "address": "1600 Amphitheatre Pkwy, Mountain View, CA 94043, USA",
          "is_current": true,
          "item_type": "Vehicle",
          "item_id": 1388383,
          "vehicle_id": 1388383,
          "location": "POINT (-122.084274 37.421688)",
          "address_components": {
            "street_number": "1600",
            "street": "Amphitheatre Parkway",
            "city": "Mountain View",
            "region": "California",
            "region_short": "CA",
            "country": "United States",
            "country_short": "US",
            "postal_code": "94043"
          },
          "geolocation": {
            "latitude": 37.421688,
            "longitude": -122.084274
          }
        }
      },
      {
        "id": 1388384,
        "account_id": 18,
        "archived_at": null,
        "fuel_type_id": null,
        "fuel_type_name": null,
        "fuel_volume_units": "us_gallons",
        "group_id": 251830,
        "group_name": "001 TEST Subgroup",
        "meter_unit": "mi",
        "name": "00 Group Test SubGroup",
        "ownership": "Owned",
        "secondary_meter": false,
        "secondary_meter_unit": null,
        "system_of_measurement": "metric",
        "vehicle_status_id": 400444,
        "vehicle_status_name": "Rented",
        "vehicle_status_color": "maroon",
        "vehicle_type_id": 144,
        "vehicle_type_name": "Car",
        "fuel_entries_count": 2,
        "service_entries_count": 1,
        "service_reminders_count": 0,
        "vehicle_renewal_reminders_count": 0,
        "comments_count": 0,
        "documents_count": 0,
        "images_count": 1,
        "current_location_entry_id": 173251066,
        "is_sample": false,
        "in_service_date": "2021-06-23",
        "in_service_meter": null,
        "estimated_service_months": null,
        "estimated_replacement_mileage": null,
        "estimated_resale_price": {
          "cents": 4500,
          "currency_iso": "USD"
        },
        "out_of_service_date": null,
        "out_of_service_meter": null,
        "meter_name": "Odometer",
        "secondary_meter_name": "Secondary Meter",
        "primary_meter_usage_per_day": "0.0",
        "secondary_meter_usage_per_day": "0.0",
        "created_at": "2021-02-28T16:43:28.569-08:00",
        "updated_at": "2022-10-31T22:22:42.754-07:00",
        "current_meter_value": 1,
        "current_meter_date": "2022-05-05",
        "secondary_meter_value": 0,
        "secondary_meter_date": null,
        "group_ancestry": "001 TEST Parent / 001 TEST Subgroup",
        "color": null,
        "license_plate": null,
        "make": "text",
        "model": "Text",
        "registration_expiration_month": 0,
        "registration_state": null,
        "trim": "text",
        "vin": "12345678901234567",
        "year": null,
        "loan_account_number": "5",
        "loan_ended_at": "2023-09-01",
        "loan_interest_rate": null,
        "loan_notes": "5",
        "loan_started_at": "2022-08-01",
        "loan_vendor_id": 774886,
        "loan_vendor_name": "11X TEST",
        "loan_amount": null,
        "loan_payment": 500,
        "residual_value": 100,
        "custom_fields": {
          "telematics_subscription": "",
          "restrict": "",
          "warranty_expiration": "2021-06-19",
          "warranty_type": "",
          "toll_pass_number": "",
          "rear_camera_enabled": "false",
          "vehicle_cleanliness": "false",
          "test": "false",
          "checkbox_filter_test": "false",
          "manufacturer_model": "",
          "extra_rextra_read_all_about_it_this_is_a_super_long_field_name_my_guyyy": ""
        },
        "inspection_schedules_count": 12,
        "issues_count": 0,
        "work_orders_count": 7,
        "type_name": "Car",
        "default_image_url": "https://d8g9nhlfs6lwh.cloudfront.net/8DcONM6nTwGbtvYzTeWQ?signature=b14f2dada779027b1b25716d4cbc792189f28b6e90c4931e09909e7240cfbe24&policy=eyJoYW5kbGUiOiI4RGNPTk02blR3R2J0dll6VGVXUSIsImV4cGlyeSI6NDUzNDk0OTM0MywiY2FsbCI6WyJyZWFkIl19",
        "default_image_url_medium": "https://d8g9nhlfs6lwh.cloudfront.net/security=policy:eyJoYW5kbGUiOiI4RGNPTk02blR3R2J0dll6VGVXUSIsImV4cGlyeSI6NDUzNDk0OTM0MywiY2FsbCI6WyJyZWFkIiwiY29udmVydCJdfQ==,signature:6349558953ea37c063a6051c4b6c936b9c17a86cca2586bbbcebf3d172e411df/resize=w:100,h:100,fit:crop/cache=expiry:max/rotate=exif:true/8DcONM6nTwGbtvYzTeWQ",
        "default_image_url_small": "https://d8g9nhlfs6lwh.cloudfront.net/security=policy:eyJoYW5kbGUiOiI4RGNPTk02blR3R2J0dll6VGVXUSIsImV4cGlyeSI6NDUzNDk0OTM0MywiY2FsbCI6WyJyZWFkIiwiY29udmVydCJdfQ==,signature:6349558953ea37c063a6051c4b6c936b9c17a86cca2586bbbcebf3d172e411df/resize=w:45,h:45,fit:crop/cache=expiry:max/rotate=exif:true/8DcONM6nTwGbtvYzTeWQ",
        "default_image_url_large": "https://d8g9nhlfs6lwh.cloudfront.net/security=policy:eyJoYW5kbGUiOiI4RGNPTk02blR3R2J0dll6VGVXUSIsImV4cGlyeSI6NDUzNDk0OTM0MywiY2FsbCI6WyJyZWFkIiwiY29udmVydCJdfQ==,signature:6349558953ea37c063a6051c4b6c936b9c17a86cca2586bbbcebf3d172e411df/resize=w:450,fit:scale/cache=expiry:max/rotate=exif:true/8DcONM6nTwGbtvYzTeWQ",
        "driver": {},
        "specs": {
          "id": 2889172,
          "vehicle_id": 1388384,
          "account_id": 18,
          "body_type": null,
          "body_subtype": null,
          "drive_type": null,
          "brake_system": null,
          "msrp_cents": 0,
          "fuel_tank_capacity": null,
          "fuel_tank_2_capacity": null,
          "front_track_width": null,
          "ground_clearance": null,
          "height": null,
          "length": null,
          "rear_track_width": null,
          "width": null,
          "wheelbase": null,
          "front_tire_psi": null,
          "rear_tire_psi": null,
          "base_towing_capacity": null,
          "curb_weight": null,
          "gross_vehicle_weight_rating": null,
          "bed_length": null,
          "max_payload": null,
          "rear_axle_type": "",
          "front_tire_type": "",
          "front_wheel_diameter": "",
          "rear_tire_type": "",
          "rear_wheel_diameter": "",
          "epa_city": null,
          "epa_highway": null,
          "epa_combined": null,
          "engine_description": "",
          "engine_brand": "",
          "engine_aspiration": null,
          "engine_block_type": null,
          "engine_bore": null,
          "engine_cam_type": null,
          "engine_compression": null,
          "engine_cylinders": null,
          "engine_displacement": null,
          "fuel_induction": null,
          "fuel_quality": "",
          "max_hp": null,
          "max_torque": null,
          "oil_capacity": null,
          "redline_rpm": "",
          "engine_stroke": null,
          "engine_valves": null,
          "transmission_description": "",
          "transmission_brand": "",
          "transmission_type": null,
          "transmission_gears": null,
          "cargo_volume": null,
          "interior_volume": null,
          "passenger_volume": "",
          "created_at": "2022-08-01T12:39:46.810-07:00",
          "updated_at": "2022-08-01T12:39:46.810-07:00",
          "duty_type": null,
          "weight_class": null,
          "engine_bore_with_units": null,
          "wheelbase_with_units": null,
          "msrp": 0
        },
        "external_ids": {
          "clearpathgps": null,
          "external_fuel_id": null,
          "fuel_id": null,
          "task_code": null,
          "traxxis_id": null
        },
        "ai_enabled": false,
        "assetable_type": "Vehicle",
        "current_location_entry": {}
      },
      {
        "id": 1388385,
        "account_id": 18,
        "archived_at": null,
        "fuel_type_id": null,
        "fuel_type_name": null,
        "fuel_volume_units": "us_gallons",
        "group_id": 251831,
        "group_name": "001 TEST Subsubgroup",
        "meter_unit": "mi",
        "name": "00 Group Test SubSubGroup",
        "ownership": "Owned",
        "secondary_meter": false,
        "secondary_meter_unit": null,
        "system_of_measurement": "metric",
        "vehicle_status_id": 3261,
        "vehicle_status_name": "Active",
        "vehicle_status_color": "blue",
        "vehicle_type_id": 144,
        "vehicle_type_name": "Car",
        "fuel_entries_count": 1,
        "service_entries_count": 0,
        "service_reminders_count": 0,
        "vehicle_renewal_reminders_count": 0,
        "comments_count": 0,
        "documents_count": 0,
        "images_count": 0,
        "current_location_entry_id": 252318659,
        "is_sample": false,
        "in_service_date": null,
        "in_service_meter": null,
        "estimated_service_months": 120,
        "estimated_replacement_mileage": 100000,
        "estimated_resale_price": {
          "cents": 0,
          "currency_iso": "USD"
        },
        "out_of_service_date": null,
        "out_of_service_meter": null,
        "meter_name": "Odometer",
        "secondary_meter_name": "Secondary Meter",
        "primary_meter_usage_per_day": "0.0",
        "secondary_meter_usage_per_day": "0.0",
        "created_at": "2021-02-28T16:43:29.160-08:00",
        "updated_at": "2022-10-31T22:23:13.866-07:00",
        "current_meter_value": 50,
        "current_meter_date": "2022-04-07",
        "secondary_meter_value": 0,
        "secondary_meter_date": null,
        "group_ancestry": "001 TEST Parent / 001 TEST Subgroup / 001 TEST Subsubgroup",
        "color": null,
        "license_plate": null,
        "make": null,
        "model": null,
        "registration_expiration_month": 0,
        "registration_state": null,
        "trim": null,
        "vin": null,
        "year": 555,
        "loan_account_number": "55",
        "loan_ended_at": "2023-06-01",
        "loan_interest_rate": null,
        "loan_notes": "55",
        "loan_started_at": "2022-06-01",
        "loan_vendor_id": 774886,
        "loan_vendor_name": "11X TEST",
        "loan_amount": null,
        "loan_payment": 500,
        "residual_value": 100,
        "custom_fields": {
          "telematics_subscription": "",
          "restrict": "",
          "warranty_expiration": "",
          "warranty_type": "",
          "toll_pass_number": "",
          "rear_camera_enabled": "false",
          "vehicle_cleanliness": "false",
          "test": "false",
          "checkbox_filter_test": "false",
          "manufacturer_model": "",
          "extra_rextra_read_all_about_it_this_is_a_super_long_field_name_my_guyyy": ""
        },
        "inspection_schedules_count": 13,
        "issues_count": 0,
        "work_orders_count": 4,
        "type_name": "Car",
        "default_image_url": null,
        "default_image_url_medium": null,
        "default_image_url_small": null,
        "default_image_url_large": null,
        "driver": {
          "id": 88607,
          "first_name": "Demo",
          "last_name": "User",
          "full_name": "Demo User",
          "default_image_url": null
        },
        "specs": {
          "id": 2889183,
          "vehicle_id": 1388385,
          "account_id": 18,
          "body_type": null,
          "body_subtype": null,
          "drive_type": null,
          "brake_system": null,
          "msrp_cents": 0,
          "fuel_tank_capacity": null,
          "fuel_tank_2_capacity": null,
          "front_track_width": null,
          "ground_clearance": null,
          "height": null,
          "length": null,
          "rear_track_width": null,
          "width": null,
          "wheelbase": null,
          "front_tire_psi": null,
          "rear_tire_psi": null,
          "base_towing_capacity": null,
          "curb_weight": null,
          "gross_vehicle_weight_rating": null,
          "bed_length": null,
          "max_payload": null,
          "rear_axle_type": "",
          "front_tire_type": "",
          "front_wheel_diameter": "",
          "rear_tire_type": "",
          "rear_wheel_diameter": "",
          "epa_city": null,
          "epa_highway": null,
          "epa_combined": null,
          "engine_description": "",
          "engine_brand": "",
          "engine_aspiration": null,
          "engine_block_type": null,
          "engine_bore": null,
          "engine_cam_type": null,
          "engine_compression": null,
          "engine_cylinders": null,
          "engine_displacement": null,
          "fuel_induction": null,
          "fuel_quality": "",
          "max_hp": null,
          "max_torque": null,
          "oil_capacity": null,
          "redline_rpm": "",
          "engine_stroke": null,
          "engine_valves": null,
          "transmission_description": "",
          "transmission_brand": "",
          "transmission_type": null,
          "transmission_gears": null,
          "cargo_volume": null,
          "interior_volume": null,
          "passenger_volume": "",
          "created_at": "2022-08-01T12:41:25.048-07:00",
          "updated_at": "2022-08-01T12:41:25.048-07:00",
          "duty_type": null,
          "weight_class": null,
          "engine_bore_with_units": null,
          "wheelbase_with_units": null,
          "msrp": 0
        },
        "external_ids": {
          "clearpathgps": null,
          "external_fuel_id": null,
          "fuel_id": null,
          "task_code": null,
          "traxxis_id": null
        },
        "ai_enabled": false,
        "assetable_type": "Vehicle",
        "current_location_entry": {
          "id": 252318659,
          "locatable_type": "FuelEntry",
          "locatable_id": 27210285,
          "date": "2021-12-03T11:04:00.000-06:00",
          "created_at": "2021-12-10T10:29:57.019-06:00",
          "updated_at": "2022-04-04T14:14:29.910-05:00",
          "contact_id": null,
          "address": "100 Green Springs Hwy, Birmingham, AL 35209, USA",
          "is_current": true,
          "item_type": "Vehicle",
          "item_id": 1388385,
          "vehicle_id": 1388385,
          "location": "POINT (-86.8248189 33.470389)",
          "address_components": {
            "street_number": "100",
            "street": "Green Springs Highway",
            "city": "Birmingham",
            "region": "Alabama",
            "region_short": "AL",
            "country": "United States",
            "country_short": "US",
            "postal_code": "35209"
          },
          "geolocation": {
            "latitude": 33.470389,
            "longitude": -86.8248189
          }
        }
      },
      {
        "id": 153,
        "account_id": 18,
        "archived_at": null,
        "fuel_type_id": 163551,
        "fuel_type_name": "5-HD Propane",
        "fuel_volume_units": "liters",
        "group_id": 861166,
        "group_name": "000 test parent to delete",
        "meter_unit": "km",
        "name": "0M4HH0",
        "ownership": "Leased",
        "secondary_meter": true,
        "secondary_meter_unit": "hr",
        "system_of_measurement": "imperial",
        "vehicle_status_id": 4061,
        "vehicle_status_name": "Sold",
        "vehicle_status_color": "gray",
        "vehicle_type_id": 144,
        "vehicle_type_name": "Car",
        "fuel_entries_count": 317,
        "service_entries_count": 249,
        "service_reminders_count": 39,
        "vehicle_renewal_reminders_count": 6,
        "comments_count": 87,
        "documents_count": 26,
        "images_count": 22,
        "current_location_entry_id": 400507019,
        "is_sample": false,
        "in_service_date": "2019-06-12",
        "in_service_meter": 1000,
        "estimated_service_months": 5,
        "estimated_replacement_mileage": 200000,
        "estimated_resale_price": {
          "cents": 1400,
          "currency_iso": "USD"
        },
        "out_of_service_date": null,
        "out_of_service_meter": null,
        "meter_name": "Odometer",
        "secondary_meter_name": "Secondary Meter",
        "primary_meter_usage_per_day": "79.0",
        "secondary_meter_usage_per_day": "2.0",
        "created_at": "2011-08-17T14:55:04.202-07:00",
        "updated_at": "2022-11-10T05:28:28.891-08:00",
        "current_meter_value": 5033029,
        "current_meter_date": "2022-08-24",
        "secondary_meter_value": 5129,
        "secondary_meter_date": "2022-05-27",
        "group_ancestry": "000 test parent to delete",
        "color": "Red",
        "license_plate": null,
        "make": "text",
        "model": null,
        "registration_expiration_month": 8,
        "registration_state": "AL",
        "trim": "EXT",
        "vin": "DASDA",
        "year": 2013,
        "loan_account_number": "13151235",
        "loan_ended_at": "2020-03-26",
        "loan_interest_rate": null,
        "loan_notes": "Great deal!",
        "loan_started_at": "2020-03-16",
        "loan_vendor_id": null,
        "loan_vendor_name": null,
        "loan_amount": null,
        "loan_payment": 700,
        "residual_value": 15000,
        "custom_fields": {
          "telematics_subscription": "Subscription B",
          "restrict": "",
          "warranty_expiration": "",
          "warranty_type": "",
          "toll_pass_number": "Text",
          "rear_camera_enabled": "true",
          "vehicle_cleanliness": "false",
          "test": "false",
          "checkbox_filter_test": "true",
          "manufacturer_model": "text",
          "extra_rextra_read_all_about_it_this_is_a_super_long_field_name_my_guyyy": ""
        },
        "inspection_schedules_count": 23,
        "issues_count": 146,
        "work_orders_count": 196,
        "type_name": "Car",
        "default_image_url": "https://d8g9nhlfs6lwh.cloudfront.net/ShLVkUYfTHK2pCM5VrLe?signature=032b16460d0d1f1e49cc23cba875bc2ae1f1e15ff6ddb60a3d47e36e41ccd606&policy=eyJoYW5kbGUiOiJTaExWa1VZZlRISzJwQ001VnJMZSIsImV4cGlyeSI6NDUzNDk0OTM0MywiY2FsbCI6WyJyZWFkIl19",
        "default_image_url_medium": "https://d8g9nhlfs6lwh.cloudfront.net/security=policy:eyJoYW5kbGUiOiJTaExWa1VZZlRISzJwQ001VnJMZSIsImV4cGlyeSI6NDUzNDk0OTM0MywiY2FsbCI6WyJyZWFkIiwiY29udmVydCJdfQ==,signature:c22a0f59cc1d13a64b33e5bafbd38b94ee9e8d0f94539e741821b99a964f22a6/resize=w:100,h:100,fit:crop/cache=expiry:max/rotate=exif:true/ShLVkUYfTHK2pCM5VrLe",
        "default_image_url_small": "https://d8g9nhlfs6lwh.cloudfront.net/security=policy:eyJoYW5kbGUiOiJTaExWa1VZZlRISzJwQ001VnJMZSIsImV4cGlyeSI6NDUzNDk0OTM0MywiY2FsbCI6WyJyZWFkIiwiY29udmVydCJdfQ==,signature:c22a0f59cc1d13a64b33e5bafbd38b94ee9e8d0f94539e741821b99a964f22a6/resize=w:45,h:45,fit:crop/cache=expiry:max/rotate=exif:true/ShLVkUYfTHK2pCM5VrLe",
        "default_image_url_large": "https://d8g9nhlfs6lwh.cloudfront.net/security=policy:eyJoYW5kbGUiOiJTaExWa1VZZlRISzJwQ001VnJMZSIsImV4cGlyeSI6NDUzNDk0OTM0MywiY2FsbCI6WyJyZWFkIiwiY29udmVydCJdfQ==,signature:c22a0f59cc1d13a64b33e5bafbd38b94ee9e8d0f94539e741821b99a964f22a6/resize=w:450,fit:scale/cache=expiry:max/rotate=exif:true/ShLVkUYfTHK2pCM5VrLe",
        "driver": {},
        "specs": {
          "id": 2920622,
          "vehicle_id": 153,
          "account_id": 18,
          "body_type": "Full",
          "body_subtype": "",
          "drive_type": "4X4",
          "brake_system": "Helium",
          "msrp_cents": 3491500,
          "fuel_tank_capacity": 30,
          "fuel_tank_2_capacity": null,
          "front_track_width": 53,
          "ground_clearance": 24,
          "height": 6,
          "length": 15,
          "rear_track_width": 52,
          "width": 8,
          "wheelbase": 120,
          "front_tire_psi": 30,
          "rear_tire_psi": 30,
          "base_towing_capacity": 8000,
          "curb_weight": 3500,
          "gross_vehicle_weight_rating": 10000,
          "bed_length": 72,
          "max_payload": 1500,
          "rear_axle_type": "",
          "front_tire_type": "Bridgestone",
          "front_wheel_diameter": "19",
          "rear_tire_type": "Bridgestone",
          "rear_wheel_diameter": "19",
          "epa_city": 15,
          "epa_highway": 19,
          "epa_combined": 17,
          "engine_description": "65191131861197",
          "engine_brand": "",
          "engine_aspiration": "Naturally Aspirated",
          "engine_block_type": "Vjjjjj",
          "engine_bore": 60,
          "engine_cam_type": "OHV",
          "engine_compression": 1.2,
          "engine_cylinders": 6,
          "engine_displacement": 2143,
          "fuel_induction": "Direct Injection",
          "fuel_quality": "87",
          "max_hp": 125,
          "max_torque": 600,
          "oil_capacity": 5,
          "redline_rpm": "801",
          "engine_stroke": 60,
          "engine_valves": 12,
          "transmission_description": "AUTO 7 GEARS",
          "transmission_brand": "Ford",
          "transmission_type": "A",
          "transmission_gears": 7,
          "cargo_volume": 100,
          "interior_volume": 500,
          "passenger_volume": "300",
          "created_at": "2022-08-10T17:38:39.416-07:00",
          "updated_at": "2022-08-10T17:38:39.416-07:00",
          "duty_type": null,
          "weight_class": null,
          "engine_bore_with_units": "60 in",
          "wheelbase_with_units": "120 in",
          "msrp": 34915
        },
        "external_ids": {
          "clearpathgps": "",
          "external_fuel_id": "",
          "fuel_id": "22",
          "task_code": "",
          "traxxis_id": "11"
        },
        "ai_enabled": false,
        "assetable_type": "Vehicle",
        "current_location_entry": {
          "id": 400507019,
          "locatable_type": "SubmittedInspectionForm",
          "locatable_id": 26611051,
          "date": "2022-10-14T22:13:49.158-07:00",
          "created_at": "2022-10-14T22:25:38.494-07:00",
          "updated_at": "2022-10-14T22:36:05.394-07:00",
          "contact_id": null,
          "address": "1600 Amphitheatre Pkwy, Mountain View, CA 94043, USA",
          "is_current": true,
          "item_type": "Vehicle",
          "item_id": 153,
          "vehicle_id": 153,
          "location": "POINT (-122.08392 37.422092)",
          "address_components": {
            "street_number": "1600",
            "street": "Amphitheatre Parkway",
            "city": "Mountain View",
            "region": "California",
            "region_short": "CA",
            "country": "United States",
            "country_short": "US",
            "postal_code": "94043"
          },
          "geolocation": {
            "latitude": 37.422092,
            "longitude": -122.08392
          }
        }
      },
      {
        "id": 747655,
        "account_id": 18,
        "archived_at": null,
        "fuel_type_id": 83886,
        "fuel_type_name": "Aviation Fuel",
        "fuel_volume_units": "uk_gallons",
        "group_id": 296595,
        "group_name": "Mallory's Group",
        "meter_unit": "hr",
        "name": "1992 Acura Vigor",
        "ownership": "Owned",
        "secondary_meter": false,
        "secondary_meter_unit": null,
        "system_of_measurement": "metric",
        "vehicle_status_id": 3263,
        "vehicle_status_name": "In Shop",
        "vehicle_status_color": "orange",
        "vehicle_type_id": 144,
        "vehicle_type_name": "Car",
        "fuel_entries_count": 15,
        "service_entries_count": 30,
        "service_reminders_count": 0,
        "vehicle_renewal_reminders_count": 0,
        "comments_count": 3,
        "documents_count": 2,
        "images_count": 4,
        "current_location_entry_id": 375726445,
        "is_sample": false,
        "in_service_date": null,
        "in_service_meter": null,
        "estimated_service_months": null,
        "estimated_replacement_mileage": null,
        "estimated_resale_price": {
          "cents": 0,
          "currency_iso": "USD"
        },
        "out_of_service_date": null,
        "out_of_service_meter": null,
        "meter_name": "Hour Meter",
        "secondary_meter_name": "Secondary Meter",
        "primary_meter_usage_per_day": "852.8",
        "secondary_meter_usage_per_day": "1.3",
        "created_at": "2019-07-19T12:22:10.333-07:00",
        "updated_at": "2022-08-24T07:19:07.095-07:00",
        "current_meter_value": 1000005,
        "current_meter_date": "2022-08-24",
        "secondary_meter_value": 8000,
        "secondary_meter_date": "2021-05-26",
        "group_ancestry": "Mallory's Group",
        "color": null,
        "license_plate": "ABC",
        "make": "Acura",
        "model": "Vigor",
        "registration_expiration_month": 0,
        "registration_state": null,
        "trim": "GS",
        "vin": "HTTP://COOKOUTMILKSHAKEREVIEWS.COM/",
        "year": 1992,
        "loan_account_number": null,
        "loan_ended_at": null,
        "loan_interest_rate": null,
        "loan_notes": null,
        "loan_started_at": null,
        "loan_vendor_id": null,
        "loan_vendor_name": null,
        "custom_fields": {
          "telematics_subscription": "",
          "restrict": "",
          "warranty_expiration": "",
          "warranty_type": "",
          "toll_pass_number": "",
          "rear_camera_enabled": "false",
          "vehicle_cleanliness": "false",
          "test": "false",
          "checkbox_filter_test": "false",
          "manufacturer_model": "",
          "extra_rextra_read_all_about_it_this_is_a_super_long_field_name_my_guyyy": ""
        },
        "inspection_schedules_count": 10,
        "issues_count": 31,
        "work_orders_count": 55,
        "type_name": "Car",
        "default_image_url": null,
        "default_image_url_medium": null,
        "default_image_url_small": null,
        "default_image_url_large": null,
        "driver": {},
        "specs": {
          "id": 2408548,
          "vehicle_id": 747655,
          "account_id": 18,
          "body_type": "Sedan",
          "body_subtype": "",
          "drive_type": "FWD",
          "brake_system": "",
          "msrp_cents": 0,
          "fuel_tank_capacity": 17,
          "fuel_tank_2_capacity": null,
          "front_track_width": null,
          "ground_clearance": 12.95,
          "height": 136.91,
          "length": 483.62,
          "rear_track_width": null,
          "width": 178.05,
          "wheelbase": 280.42,
          "front_tire_psi": null,
          "rear_tire_psi": null,
          "base_towing_capacity": null,
          "curb_weight": 1456.94,
          "gross_vehicle_weight_rating": null,
          "bed_length": null,
          "max_payload": null,
          "rear_axle_type": "",
          "front_tire_type": "",
          "front_wheel_diameter": "15",
          "rear_tire_type": "",
          "rear_wheel_diameter": "15",
          "epa_city": 18,
          "epa_highway": 24,
          "epa_combined": 20,
          "engine_description": "2L NA I5 single overhead cam (SOHC) 20V",
          "engine_brand": "test",
          "engine_aspiration": "Naturally Aspirated",
          "engine_block_type": "I",
          "engine_bore": null,
          "engine_cam_type": "SOHC",
          "engine_compression": 0,
          "engine_cylinders": 5,
          "engine_displacement": 2.5,
          "fuel_induction": "Fuel Injection",
          "fuel_quality": "",
          "max_hp": 176,
          "max_torque": 170,
          "oil_capacity": 1000,
          "redline_rpm": "0",
          "engine_stroke": 0,
          "engine_valves": 20,
          "transmission_description": "5-Speed Manual",
          "transmission_brand": "",
          "transmission_type": "Manual",
          "transmission_gears": 5,
          "cargo_volume": null,
          "interior_volume": null,
          "passenger_volume": "",
          "created_at": "2022-02-16T12:37:52.653-08:00",
          "updated_at": "2022-02-16T12:37:52.653-08:00",
          "duty_type": null,
          "weight_class": null,
          "engine_bore_with_units": null,
          "wheelbase_with_units": "280.4 cm",
          "msrp": 0
        },
        "external_ids": {
          "clearpathgps": "",
          "external_fuel_id": "",
          "fuel_id": "",
          "task_code": "",
          "traxxis_id": ""
        },
        "ai_enabled": false,
        "assetable_type": "Vehicle",
        "current_location_entry": {
          "id": 375726445,
          "locatable_type": "SubmittedInspectionForm",
          "locatable_id": 25064129,
          "date": "2022-08-31T06:29:35.977-10:00",
          "created_at": "2022-08-31T06:29:36.977-10:00",
          "updated_at": "2022-08-31T06:30:50.707-10:00",
          "contact_id": null,
          "address": "609 Barclay Ln, Birmingham, AL 35206, USA",
          "is_current": true,
          "item_type": "Vehicle",
          "item_id": 747655,
          "vehicle_id": 747655,
          "location": "POINT (-86.691986 33.584694)",
          "address_components": {
            "street_number": "609",
            "street": "Barclay Lane",
            "city": "Birmingham",
            "region": "Alabama",
            "region_short": "AL",
            "country": "United States",
            "country_short": "US",
            "postal_code": "35206"
          },
          "geolocation": {
            "latitude": 33.584694,
            "longitude": -86.691986
          }
        }
      }
    ]
    """
}